SANITIZER_TOOL_DIR ?= ../nv-compute

NV_NVBIT_DIR ?= ../nv-nvbit

CPP_TRACE_DIR ?= cpp_trace/cpp_trace

PY_FRAME_DIR ?= py_frame/py_frame

PAR_HASHMAP_INC_DIR ?= ../third_party/parallel-hashmap

INSTALL_DIR ?= ../build/sanalyzer
